                                     Numpy

'''<br>

@Author: Venkatesh <br>
@Date: 2024-08-21 18:00:30 <br>
@Last Modified by: Author Name <br>
@Last Modified time: 2024-08-21 18:00:30 <br>
@Title : Program numpy  <br>

''' 

In [50]:
import numpy as np
import os


1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.

In [51]:
def one_dimention_print_method(list_items):
    '''
          Description: 
                this function is converting list to float array one dimentional
          Parameters: 
                list_items(list_items):list of items
          Return : 
                returns one dimentional numpy array
    '''
    result_array=np.asarray(list_items,dtype=float)
    return result_array


def main():
    list_items=[12.23,13.32,100,36.32]
    print(f"One dimentional numpy array:{one_dimention_print_method(list_items)}")


if __name__=="__main__":
    main()

One dimentional numpy array:[ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.

In [52]:
def matrix_method(start,end):
    '''
          Description: 
                this function is printing 3*3 matrix 2 to 10
          Parameters: 
                start (int): starting value
                end (int): ending value
          Return : 
                returns 3*3 matrix
    '''
    result=np.arange(start,end)
    return result.reshape(3,3)


def main():

    start=int(input("enter staring value"))
    end=int(input("enter ending value ending value is exclude:"))
    print("3*3 matrix is :")
    print(f"{matrix_method(start,end)}")


if __name__=="__main__":
    main()






3*3 matrix is :
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3.Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [53]:
def changing_value(vector,position,value):
    '''
          Description: 
                this function is updating value in null vector
          Parameters: 
                vector[]: list of null vector
                postion(int): which position whant to change
                value(int): update value
          Return : 
                returns updated value postion 10 
    '''
    vector[position]=value
    return vector


def create_null_velctor():
    '''
          Description: 
                this function is creating null vector 
          Parameters: 
                no paramters
          Return : 
                returns 1d array with length 10
    '''
    
    return np.zeros(10)


def main():
    position=5
    value=11
    print("null vector:",create_null_velctor())
    print(f"after updating:{changing_value(create_null_velctor(),position,value)}")

    
if __name__=="__main__":
    main()

null vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
after updating:[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [54]:
def reversing_array(original_array):
    '''
          Description: 
                this function is reversing an array
          Parameters: 
                original_array: a list of array items
          Return : 
                None
    '''
    print("original array:",original_array)
    reverse_result=original_array[::-1]
    print("reversing array:",reverse_result)


def main():

    original_array=np.arange(12,38)
    reversing_array(original_array)


if __name__=="__main__":
    main()

original array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
reversing array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [55]:
def array_border_ones(original_array):
    '''
          Description: 
                this function is adding 0's in inside 2d array borders 1's
          Parameters: 
                original_array: a list of array items
          Return : 
                None
    '''
    print("original array:")
    print(original_array)
    original_array[1:-1,1:-1]=0
    print("1 border 0 inside in array:")
    print(original_array)


def main():

    original_array=np.ones([5,5])
    array_border_ones(original_array)


if __name__=="__main__":
    main()

original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 border 0 inside in array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [56]:
def array_border_zeros(original_array):
    '''
          Description: 
                this function is adding 0's in inside 2d array borders 1's
          Parameters: 
                original_array: a list of array items
          Return : 
                None
    '''
    print("original array:")
    print(original_array)
    original_array[1:-1,1:-1]=1
    print("0 border 1 inside in array:")
    print(original_array)


def main():

    original_array=np.zeros([5,5])
    array_border_zeros(original_array)


if __name__=="__main__":
    main()

original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
0 border 1 inside in array:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7.Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [57]:
def check_board_pattern(original_array):
    '''
          Description: 
                this function is check board pattern 0's and 1's
          Parameters: 
                original_array: a list of array items
          Return : 
                returns 8*8 matrix check board pattern
    '''
    original_array[1::2,::2]=1
    original_array[::2,1::2]=1
    print("check board pattern:")
    return original_array


def main():

    original_array=np.zeros([8,8])
    print(check_board_pattern(original_array))


if __name__=="__main__":
    main()

check board pattern:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [58]:
def conver_list_array(list_ex):
    '''
          Description: 
                this function is convering list to array
          Parameters: 
                list[]: list of items
          Return : 
                returns list tuple into array
    '''
    result_array=np.array(list_ex,dtype=int)
    print("list to array:")
    return result_array


def conver_tuple_array(tuple_ex):
    '''
          Description: 
                this function is convering list to array
          Parameters: 
                list[]: list of items
          Return : 
                None
    '''
    result_array=np.array(tuple_ex,dtype=int)
    print("tuple to array:")
    print(result_array)


def main():
    list_ex=[1,2,3,4,5,6,7,8]
    tuple_ex=([8,4,6],[1,2,3])
    conver_list_array(list_ex)
    conver_tuple_array(tuple_ex)


if __name__=="__main__":
    main()

list to array:
tuple to array:
[[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [59]:
def values_appending(original_array,adding_values_array):
    '''
          Description: 
                this function is adding values in array
          Parameters: 
                origin_array[]: list of items
                adding_values_array[]: new values to adding orginal array
          Return : 
                None
    '''
    original_array=np.array(original_array)
    print("original array:")
    print(original_array)
    updated_array=np.append(original_array,adding_values_array)
    print("after appending")
    print(updated_array)



def main():
    original_array=[10,20,30]
    adding_values_array=[40,50,60,70,80,90]
    values_appending(original_array,adding_values_array)


if __name__=="__main__":
    main()

original array:
[10 20 30]
after appending
[10 20 30 40 50 60 70 80 90]


10.Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [60]:
def identify_real_imag(original_array):
    '''
          Description: 
                this function is identify real and imaginary parts
          Parameters: 
                origin_array[]: list of items
          Return : 
                None
    '''
    original_array=np.array(original_array)
    print("original array:")
    print(original_array)
    real_part=np.real(original_array)
    print("real part of array:")
    print(real_part)
    imag_part=np.imag(original_array)
    print("Imaginary part of the array:")
    print(imag_part)



def main():
    original_array=[ 1.00000000+0.j ,0.70710678+0.70710678j]
    identify_real_imag(original_array)


if __name__=="__main__":
    main()

original array:
[1.   +0.j    0.707+0.707j]
real part of array:
[1.    0.707]
Imaginary part of the array:
[0.    0.707]


11.Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [61]:
def size_array(original_array):
    '''
          Description: 
                this function is get size of array
          Parameters: 
                origin_array[]: list of items
          Return : 
                
    '''
    original_array=np.array(original_array)
    size_result=original_array.size
    print("size of the array:",size_result)


def length_array_bytes(original_array):
    '''
          Description: 
                this function is length of array element in bytes
          Parameters: 
                origin_array[]: list of items
          Return : 
                None
    '''
    original_array=np.array(original_array)
    length_element_bytes=original_array.itemsize
    print("length of array element in bytes:",length_element_bytes)


def total_bytes(original_array):
    '''
          Description: 
                this function is get total array elements in bytes
          Parameters: 
                origin_array[]: list of items
          Return : 
                None
    '''
    original_array=np.array(original_array)
    total_bytes=original_array.nbytes
    print("total array elements in bytes:",total_bytes)


def main():
   
   original_array=[10,12,100,34]
   size_array(original_array)
   length_array_bytes(original_array)
   total_bytes(original_array)


if __name__=="__main__":
    main()

size of the array: 4
length of array element in bytes: 8
total array elements in bytes: 32


12.Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [62]:
def common_values(array_1,array_2):
    '''
          Description: 
                this function is common values identify in two arrays
          Parameters: 
                array_1[]: list of items
                array_2[]: list of items
          Return : 
                retuerns common items in two arrays
    '''
    array_1=np.array(array_1)
    print("Array 1:")
    print(array_1)
    array_2=np.real(array_2)
    print("Array 2:")
    print(array_2)
    common=np.intersect1d(array_1,array_2)
    print("common values between two arrays:")
    return common


def main():
    array_1=[0,10,20,40,60]
    array_2=[10,30,40]
    print(common_values(array_1,array_2))


if __name__=="__main__":
    main()

Array 1:
[ 0 10 20 40 60]
Array 2:
[10 30 40]
common values between two arrays:
[10 40]


13.Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [63]:
def set_differnce_of_arrays(array_1,array_2):
    '''
          Description: 
                this function is set difference
          Parameters: 
                array_1[]: list of items
                array_2[]: list of items
          Return : 
                returns set difference between two arrays
    '''
    array_1=np.array(array_1)
    print("Array 1:")
    print(array_1)
    array_2=np.real(array_2)
    print("Array 2:")
    print(array_2)
    set_differnce=np.setdiff1d(array_1,array_2)
    print("set difference between two arrays:")
    return set_differnce


def main():
    array_1=[0,10,20,40,60,80]
    array_2=[10,30,40,50,70,90]
    print(set_differnce_of_arrays(array_1,array_2))


if __name__=="__main__":
    main()

Array 1:
[ 0 10 20 40 60 80]
Array 2:
[10 30 40 50 70 90]
set difference between two arrays:
[ 0 20 60 80]


14.Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [64]:
def set_exclive_xor(array_1,array_2):
    '''
          Description: 
                this function is set difference
          Parameters: 
                array_1[]: list of items
                array_2[]: list of items
          Return : 
                returns set exclusive of two arrays
    '''
    array_1=np.array(array_1)
    print("Array 1:")
    print(array_1)
    array_2=np.real(array_2)
    print("Array 2:")
    print(array_2)
    set_differnce=np.setxor1d(array_1,array_2)
    print("Unique values that are in only one (not both) of the input arrays:")
    return set_differnce


def main():
    array_1=[0,10,20,40,60,80]
    array_2=[10,30,40,50,70]
    print(set_exclive_xor(array_1,array_2))


if __name__=="__main__":
    main()

Array 1:
[ 0 10 20 40 60 80]
Array 2:
[10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [65]:
def comparing_method(array_a,array_b):
    '''
          Description: 
                this function is comparing two array like <,>,<=,>=
          Parameters: 
                array_a[]: list of items
                array_b[]: list of items
          Return : 
                None
    '''
    array_a=np.array(array_a)
    print("Array 1:",array_a)
    array_b=np.real(array_b)
    print("Array 2:",array_b)
    print("a>b")
    print(array_a>array_b)
    print("a>=b")
    print(array_a>=array_b)
    print("a<b")
    print(array_a<array_b)
    print(array_a<=array_b)
    print(array_a<=array_b)


def main():
    array_1=[1,2]
    array_2=[4,5]
    comparing_method(array_1,array_2)


if __name__=="__main__":
    main()

Array 1: [1 2]
Array 2: [4 5]
a>b
[False False]
a>=b
[False False]
a<b
[ True  True]
[ True  True]
[ True  True]


16. Write a Python program to save a NumPy array to a text file.

In [66]:
def convertin_array_text(original_array):
    '''
          Description: 
                this function is convert array to text
          Parameters: 
                original_array: a list of array items
          Return : 
                None
    '''
    original_array=np.array(original_array)
    np.savetxt('original_array.txt',original_array,fmt="%d")
    print("Array has been saved to original_array.txt")


def main():

    original_array=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
    convertin_array_text(original_array)


if __name__=="__main__":
    main()

Array has been saved to original_array.txt


17. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [67]:
def continiuos_flatten_array(original_array):
    '''
          Description: 
                this function is convert array to text
          Parameters: 
                original_array: a list of array items
          Return : 
                returns flatten array
    '''
    original_array=np.array(original_array)
    print("original array:")
    print(original_array)
    flatten_array=original_array.flatten()
    print("new flatten array:")
    return flatten_array


def main():

    original_array=[[10, 20, 30], [20, 40, 50]]
    print(continiuos_flatten_array(original_array))


if __name__=="__main__":
    main()

original array:
[[10 20 30]
 [20 40 50]]
new flatten array:
[10 20 30 20 40 50]


18.Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [68]:
def change_data_type_array(original_array):
    '''
          Description: 
                this function is convert int to float array
          Parameters: 
                original_array: a list of array items
          Return : 
                returns floaten array
    '''
    original_array=np.array(original_array)
    print("original array:")
    print(original_array)
    print("Data type of the array is:",original_array.dtype)
    floaten_array=original_array.astype(np.float64)
    print("new type",floaten_array.dtype)
    return floaten_array


def main():

    original_array=[[10, 20, 30], [20, 40, 50]]
    print(change_data_type_array(original_array))


if __name__=="__main__":
    main()

original array:
[[10 20 30]
 [20 40 50]]
Data type of the array is: int64
new type float64
[[10. 20. 30.]
 [20. 40. 50.]]


19. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [69]:
def three_d_array():
    '''
          Description: 
                this function is create a 3-D array with ones on a diagonal and zeros
                elsewhere.
          Parameters: 
                no perameters
          Return : 
                returns zeroes and eye method use
    '''
    result=np.eye(3)
    return result


def main():
    print(three_d_array())


if __name__=="__main__":
    main()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


20. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]

[ 1. 1. 1.]]

In [70]:
def array_formate_change(original_array):
    '''
          Description: 
                this function is change the array 
                elsewhere.
          Parameters: 
                original[]: list of items
          Return : 
                None
    '''
    original_array[1,0]=1
    original_array[2,:2]=1
    original_array[3,:3]=1
    print(original_array)


def main():
    original_array=np.zeros((4,3))
    array_formate_change(original_array)


if __name__=="__main__":
    main()

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


21. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: [[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [71]:
def concadinate_two_d_array(array_a):
    '''
          Description: 
                this function is concinate array 
          Parameters: 
                array_a[]: list of items
          Return : 
                None
    '''
    array_a=np.array(array_a)
    result=np.concatenate(array_a,axis=1)
    print(result)
    

def main():
    array_a=[[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
    concadinate_two_d_array(array_a)


if __name__=="__main__":
    main()

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


22.Write a Python program to make an array immutable (read-only).
Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only

In [72]:
def array_immutable(array_a):
    '''
          Description: 
                this function array as immutable
          Parameters: 
                array_a[]: list of items
          Return : 
                None
    '''
    array_a=np.array(array_a)
    array_a.flags.writeable=False
    print("The test array is read only or not")
    try:
        array_a[0]=1

    except ValueError as e:
        print("Error",e)



def main():
    array_a=[30,10,20,40]
    array_immutable(array_a)


if __name__=="__main__":
    main()

The test array is read only or not
Error assignment destination is read-only


23. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
Expected Output:
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]

In [73]:
def multiple_array_with_three(array_a):
    '''
          Description: 
                this function is mutltiple array with three 
          Parameters: 
                array_a[]: list of items
          Return : 
                returns array multiply with 3
    '''
    result=array_a*3
    return result



def main():
    array_a=np.arange(12).reshape(3,4)
    print(multiple_array_with_three(array_a))


if __name__=="__main__":
    main()

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


24.Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [74]:
def array_to_list(array_a):
    '''
          Description: 
                this function isconverting array to list
          Parameters: 
                array_a[]: list of items
          Return : 
                None
    '''
    print("original arraay:")
    print(array_a)
    list_result=array_a.tolist()
    print("Array to list:")
    print(list_result)



def main():
    array_a=np.arange(6).reshape(3,2)
    array_to_list(array_a)


if __name__=="__main__":
    main()

original arraay:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:

Original array elements:
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349
0.35399976 0.99469633 0.0694458 0.54711478]
Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [75]:
def array_to_list_with_three(array_a):
    '''
          Description: 
                this function isconverting array to list array values with precision 3
          Parameters: 
                array_a[]: list of items
          Return : 
                None
    '''
    print("original array:")
    print(array_a)
    print("print value with precision 3" )
    result_list=np.around(array_a,3)
    print(result_list)



def main():
    array_a=[ 0.26153123, 0.52760141 ,0.5718299 ,0.5927067 ,0.7831874, 0.69746349,
    0.35399976 ,0.99469633, 0.0694458, 0.54711478]
    array_a=np.array(array_a)
    array_to_list_with_three(array_a)


if __name__=="__main__":
    main()

original array:
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]
print value with precision 3
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


26. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.
Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]

In [76]:
def array_to_list_with_set_precision(array_a):
    '''
          Description: 
                this function is converting array to list array values with precision 3
          Parameters: 
                array_a[]: list of items
          Return : 
                None
    '''
    print("original array:")
    print(array_a)
    print("print value with set precision 3" )
    np.set_printoptions(suppress=True, precision=3)
    print(array_a)



def main():
    array_a=[ 1.60000000e-10 ,1.60000000e+00, 1.20000000e+03, 2.35000000e-01]
    array_a=np.array(array_a)
    array_to_list_with_set_precision(array_a)


if __name__=="__main__":
    main()

original array:
[   0.       1.6   1200.       0.235]
print value with set precision 3
[   0.       1.6   1200.       0.235]


27. Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]

In [81]:
def adding_extra_column(array_a,new_column_array):
    '''
          Description: 
                this function adding new extra column 
          Parameters: 
                array_a[]: list of items
                new_column_array: new adding column items
          Return : 
                None
    '''
    print("original array:")
    print(array_a)
    print("print after adding new column" )
    result_new_columns=np.append(array_a,new_column_array,axis=1)
    print(result_new_columns)


def main():
    array_a=[ [10,20,30],[40,50,60]]
    new_column_array=[[100],[200]]
    array_a=np.array(array_a)
    new_column_array=np.array(new_column_array)
    adding_extra_column(array_a,new_column_array)


if __name__=="__main__":
    main()

original array:
[[10 20 30]
 [40 50 60]]
print after adding new column
[[ 10  20  30 100]
 [ 40  50  60 200]]
